### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by potatochick2020** [Mango0x45/center#1]
I am a beginner in C and want to help a bit with this project after seeing this from hacktoberfest.
I found some bug that I don't know is this bug, but I want to improve it after I get your permission.

1. `./center ` will not exit 
![image](https://user-images.githubusercontent.com/92591333/192115623-826a05b8-2eb0-4b5f-ae3d-da929a90461f.png)

2. `./center -w (not valid width)` will have unexpected output and do not exit 

Valid width:
![image](https://user-images.githubusercontent.com/92591333/192115709-0bd26018-3efc-4156-bf44-606f2308e48a.png)

Not valid width: 
Empty after pressing enter
![image](https://user-images.githubusercontent.com/92591333/192115747-b14918de-a59f-4bf3-ab7d-9cf310e234fb.png)

After force exit by ctrl+c , and I could not find my history after I scroll up
![image](https://user-images.githubusercontent.com/92591333/192115778-ba6ffe44-f1e2-4375-995a-e5ef60671b71.png)

**Comment by Mango0x45** [comment]
This looks like intended behavior to me.  When you call `center` it reads
input from the standard input if no files are provided as command-line
arguments.  This is so that you can do preprocessing on the input with
another commands (`grep <some regex> file | center` for example).  In the
case of your screenshots, you just need to send an EOF signifying the end
of input.  You can do that with ‹ctrl-d›.
